name: virtualenv
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.11.5=py36ha569be9_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- ncurses=6.0=hd04f020_2
- openssl=1.0.2n=hdbc3d79_0
- pip=9.0.1=py36h1555ced_4
- python=3.6.3=h47c878a_7
- readline=7.0=hc1231fa_4
- setuptools=36.5.0=py36h2134326_0
- sqlite=3.20.1=h7e4c145_2
- tk=8.6.7=h35a86e2_3
- wheel=0.30.0=py36h5eb2c71_1
- xz=5.2.3=h0278029_2
- zlib=1.2.11=hf3cbc9b_2
- pip:
  - chardet==3.0.4
  - cycler==0.10.0
  - idna==2.6
  - matplotlib==2.1.1
  - numpy==1.13.3
  - pandas==0.21.1
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.3
  - requests==2.18.4
  - six==1.11.0
  - urllib3==1.22
prefix: /Users/simransethi/anaconda3/envs/virtualenv

